# Generated by Django 4.1.6 on 2023-02-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='phoneverificationtoken',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='twofactorauthtoken',
            name='salt',
        ),
    ]
