version: '3.9'

services:
  api:
    build:
      context: ./api
    command: daphne -b 0.0.0.0 -p 8000 simplepasswords_api.asgi:application
    secrets:
      - aws_ses_key
      - aws_ses_password
      - db_default_name
      - db_default_user
      - db_default_password
      - db_default_host
      - db_default_port
      - db_logger_name
      - db_logger_user
      - db_logger_password
      - db_logger_host
      - db_logger_port
      - django_secret_key
      - django_superuser_name
      - django_superuser_email
      - django_superuser_password
      - redis_password
      - twilio_account_sid
      - twilio_auth_token
      - twilio_phone_number
    env_file:
      - api.env
    environment:
      DB_DEFAULT_NAME: /run/secrets/db_default_name
      DB_DEFAULT_USER: /run/secrets/db_default_user
      DB_DEFAULT_PASSWORD: /run/secrets/db_default_password
      DB_DEFAULT_HOST: /run/secrets/db_default_host
      DB_DEFAULT_PORT: /run/secrets/db_default_port
      DB_LOGGER_NAME: /run/secrets/db_logger_name
      DB_LOGGER_USER: /run/secrets/db_logger_user
      DB_LOGGER_PASSWORD: /run/secrets/db_logger_password
      DB_LOGGER_HOST: /run/secrets/db_logger_host
      DB_LOGGER_PORT: /run/secrets/db_logger_port
      DJANGO_SUPERUSER_NAME: /run/secrets/django_superuser_name
      DJANGO_SUPERUSER_EMAIL: /run/secrets/django_superuser_email
      DJANGO_SUPERUSER_PASSWORD: /run/secrets/django_superuser_password
      EMAIL_HOST_USER: /run/secrets/aws_ses_key
      EMAIL_HOST_PASSWORD: /run/secrets/aws_ses_password
      REDIS_PASSWORD: /run/secrets/redis_password
      SECRET_KEY: /run/secrets/django_secret_key
      TWILIO_ACCOUNT_SID: /run/secrets/twilio_account_sid
      TWILIO_AUTH_TOKEN: /run/secrets/twilio_auth_token
      TWILIO_PHONE_NUMBER: /run/secrets/twilio_phone_number
    ports:
      - 8000:8000
    depends_on:
      - db_default
      - db_logger
      - redis
  frontend:
    build:
      context: ./frontend
    user: nextjs
    command: npm run start
    ports:
      - 3000:3000
    env_file:
      - frontend.env
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      NODE_ENV: production
  db_default:
    image: postgres:14
    secrets:
      - db_default_name
      - db_default_user
      - db_default_password
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_default_name
      POSTGRES_USER_FILE: /run/secrets/db_default_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_default_password
    ports:
      - 5442:5432
    volumes:
      - ./db_default/var/lib/postgresql/data:/var/lib/postgresql/data:rw
  db_logger:
    image: postgres:14
    secrets:
      - db_logger_name
      - db_logger_user
      - db_logger_password
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_logger_name
      POSTGRES_USER_FILE: /run/secrets/db_logger_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_logger_password
    ports:
      - 5452:5432
    volumes:
      - ./db_logger/var/lib/postgresql/data:/var/lib/postgresql/data:rw
  redis:
    image: redis:alpine
    restart: always
    secrets:
      - redis_password
    command: sh -c "cat /run/secrets/redis_password | xargs -0 redis-server --appendonly yes --requirepass"
    ports:
      - 6379:6379
    volumes:
      - /data
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/etc/nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./certbot/var/www/certbot/:/var/www/certbot/:ro
      - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - api
      - frontend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/var/www/certbot/:/var/www/certbot/:rw
      - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:rw
      - ./certbot/var/log/letsencrypt/:/var/log/letsencrypt/:rw
secrets:
    aws_ses_key:
      file: ./secrets/aws_ses_key.txt
    aws_ses_password:
      file: ./secrets/aws_ses_password.txt
    db_default_name:
      file: ./secrets/db_default_name.txt
    db_default_user:
      file: ./secrets/db_default_user.txt
    db_default_password:
      file: ./secrets/db_default_password.txt
    db_default_host:
      file: ./secrets/db_default_host.txt
    db_default_port:
      file: ./secrets/db_default_port.txt
    db_logger_name:
      file: ./secrets/db_logger_name.txt
    db_logger_user:
      file: ./secrets/db_logger_user.txt
    db_logger_password:
      file: ./secrets/db_logger_password.txt
    db_logger_host:
      file: ./secrets/db_logger_host.txt
    db_logger_port:
      file: ./secrets/db_logger_port.txt
    django_secret_key:
      file: ./secrets/django_secret_key.txt
    django_superuser_name:
      file: ./secrets/django_superuser_name.txt
    django_superuser_email:
      file: ./secrets/django_superuser_email.txt
    django_superuser_password:
      file: ./secrets/django_superuser_password.txt
    redis_password:
      file: ./secrets/redis_password.txt
    twilio_account_sid:
      file: ./secrets/twilio_account_sid.txt
    twilio_auth_token:
      file: ./secrets/twilio_auth_token.txt
    twilio_phone_number:
      file: ./secrets/twilio_phone_number.txt